AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      # Cors: "'www.example.com'"

  Handler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: lambda.handler
      Runtime: nodejs18.x
      Events:
        RootEndpoint:
          Type: Api
          Properties:
            Method: any
            Path: /
            RestApiId: !Ref ApiGatewayApi
        GetIt:
          Type: Api
          Properties:
            Path: /{any+}
            Method: any
            RestApiId: !Ref ApiGatewayApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - lambda.ts

Outputs:
  ApiEndpointURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub
      - "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
      - ServerlessRestApi: !Ref ApiGatewayApi
